# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle 

name: Gradle Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: 安装多平台 JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: 打包多平台 runtime
      run: ./gradlew runtime
      env:
        WIN_JDK: ${{ env.JAVA_HOME }}
        LINUX_JDK: ${{ env.JAVA_HOME }}
        MAC_JDK: ${{ env.JAVA_HOME }}

    - name: Compress runtime image  → 最小体积
      run: |
        ls -la build/image
        cd build/image
        7z a -tzip -mx=9 Javaows.zip ./*

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Upload to GitHub Release
      run: ./gradlew githubRelease
      env:
        RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}